version: 3.7

services:
  model:
    build: ./model/
    container-name: model
    ports:
      - 8888:8888
    volumes:
      - ./model:/tf:Z
    network_mode: host

  api:
    build: ./api/
    container-name: api
    ports:  
      - 5000:5000
    volumes:
      - ./api:/tf:Z
    network_mode: host
